#!/bin/bash
set -euo pipefail

echo "  Gemma 4 Cloud Deployment — Deploy"
echo ""

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TFVARS="${REPO_ROOT}/terraform/terraform.tfvars"

# Non-interactive mode. AUTO_APPROVE=1 ./scripts/deploy.sh runs end to end without
# prompting, which is what CI, cron or a piped run needs. It also fixes a trap: with
# `set -e`, a bare `read` reaching end-of-input returns 1 and kills the script with no
# message at all, so `./scripts/deploy.sh < /dev/null` used to die silently.
AUTO_APPROVE="${AUTO_APPROVE:-0}"

confirm_step() {
    if [ "$AUTO_APPROVE" = "1" ]; then
        echo "  $1 (auto-approved)"
        echo ""
        return 0
    fi

    local reply
    read -r -p "  $1 Type 'yes' to confirm: " reply || reply=""
    echo ""
    [ "$reply" = "yes" ]
}


# PREFLIGHT
# Fail early with a clear message instead of half-way through an apply.

echo "→ Preflight checks..."

for tool in terraform aws docker; do
    if ! command -v "$tool" >/dev/null; then
        echo "  Missing required tool: ${tool}. See the README for versions."
        exit 1
    fi
done

# terraform.tfvars is gitignored, so a clean clone never has one. Rather than making
# the reviewer copy the example and invent two secrets by hand, generate it: every
# setting in it either has a sensible default or is a random string nobody needs to
# choose. Environment variables override the defaults for the three that are a matter
# of taste; the keys are always random.
#
# Generated ONLY when the file is absent. The two keys end up in SSM parameters, so
# regenerating them on an existing deployment would rewrite those parameters and force
# a pointless redeployment on every single run.
if [ ! -f "$TFVARS" ]; then
    if ! command -v openssl >/dev/null; then
        echo "  Missing terraform/terraform.tfvars, and openssl is not installed to"
        echo "  generate the API keys. Install openssl, or copy"
        echo "  terraform/terraform.tfvars.example and fill in your own values."
        exit 1
    fi

    # Two separate calls, so the keys genuinely differ. variables.tf rejects a
    # configuration where they are equal — that collapses the two-tier auth into one
    # shared secret. Base64 output is A-Za-z0-9+/= only, so it needs no HCL escaping.
    GENERATED_PUBLIC_KEY=$(openssl rand -base64 24)
    GENERATED_INTERNAL_KEY=$(openssl rand -base64 24)

    cat > "$TFVARS" <<EOF
# Generated by scripts/deploy.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC').
# Not in version control. Edit it freely: deploy.sh only ever writes this file when
# it does not already exist. Delete it and the next deploy generates fresh API keys,
# which rewrites the SSM parameters and redeploys the service.
aws_region       = "${AWS_REGION:-eu-central-1}"
project_name     = "${PROJECT_NAME:-gemma-inference}"
instance_type    = "${INSTANCE_TYPE:-g6.xlarge}"
public_api_key   = "${GENERATED_PUBLIC_KEY}"
internal_api_key = "${GENERATED_INTERNAL_KEY}"
alert_email      = "${ALERT_EMAIL:-}"
EOF

    # The file holds two secrets in plaintext; keep it off other accounts on the box.
    chmod 600 "$TFVARS"

    echo "  Generated terraform/terraform.tfvars (mode 600):"
    echo "    aws_region     ${AWS_REGION:-eu-central-1}"
    echo "    project_name   ${PROJECT_NAME:-gemma-inference}"
    echo "    instance_type  ${INSTANCE_TYPE:-g6.xlarge}"
    echo "    api keys       generated with openssl rand -base64 24"

    if [ -n "${ALERT_EMAIL:-}" ]; then
        echo "    alert_email    ${ALERT_EMAIL}"
    else
        echo "    alert_email    (empty) — WARNING, no alarm emails will be sent."
        echo "                   The alarms and the SNS topic are still created; set"
        echo "                   ALERT_EMAIL=you@example.com before the first deploy,"
        echo "                   or add the address to terraform.tfvars later."
    fi
fi

if ! ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null); then
    echo "  AWS credentials are not configured. Run 'aws configure' first."
    exit 1
fi

if ! docker info >/dev/null 2>&1; then
    echo "  Docker is installed but the daemon is not running."
    exit 1
fi

# The image build is BuildKit-only: build_and_push.sh passes --provenance/--sbom
# (Buildx flags) and the vLLM Dockerfile uses RUN --mount=type=secret. Plain
# `docker build` only routes to Buildx from Docker Engine 23.0 onwards, so an older
# daemon fails at step 2 — after the state bucket and ECR repository already exist.
if ! docker buildx version >/dev/null 2>&1; then
    echo "  docker buildx is missing. The image build needs BuildKit (Docker >= 23)."
    echo "  Install the docker-buildx-plugin package, then re-run."
    exit 1
fi

# Checked here as well as in build_and_push.sh, so a missing token fails before any
# AWS resources are created rather than 10 minutes into the image build.
if [ -z "${HF_TOKEN:-}" ]; then
    echo "  HF_TOKEN is not set. The Gemma model repo is gated — accept the licence"
    echo "  on Hugging Face, then: export HF_TOKEN=hf_..."
    exit 1
fi

# Read a setting from terraform.tfvars, falling back to the default in variables.tf.
# Only the two values needed to create the state bucket are read this way, because
# that has to happen before Terraform runs. Everything else comes from outputs.
tfvar() {
    local value
    value=$(grep -E "^[[:space:]]*$1[[:space:]]*=" "$TFVARS" | head -1 | cut -d'"' -s -f2 || true)
    echo "${value:-$2}"
}

PROJECT_NAME=$(tfvar project_name gemma-inference)
REGION=$(tfvar aws_region eu-central-1)
STATE_BUCKET="${PROJECT_NAME}-tfstate-${ACCOUNT_ID}"

echo "  Account:  ${ACCOUNT_ID}"
echo "  Region:   ${REGION}"
echo "  State:    s3://${STATE_BUCKET}"

# A brand-new AWS account has a GPU quota of 0, which is the single most common way
# this stack applies cleanly and then never launches an instance. Only a warning:
# reading it needs servicequotas:GetServiceQuota, which not every deploy role has.
GPU_QUOTA=$(aws service-quotas get-service-quota \
    --service-code ec2 --quota-code L-DB2E81BA --region "$REGION" \
    --query 'Quota.Value' --output text 2>/dev/null || echo "unknown")

# Anything that is not a plain number — "unknown", "None", an empty string — is treated
# as unreadable, so a changed response shape can never reach the integer comparison.
if ! printf '%s' "$GPU_QUOTA" | grep -qE '^[0-9]+(\.[0-9]+)?$'; then
    echo "  GPU quota: could not read it — check it manually in Service Quotas."
elif [ "${GPU_QUOTA%%.*}" -lt 4 ]; then
    echo "  GPU quota: ${GPU_QUOTA%%.*} vCPU — WARNING, a g6.xlarge needs 4."
    echo "             Request 'Running On-Demand G and VT instances' in Service"
    echo "             Quotas, or the GPU task will stay pending forever."
else
    echo "  GPU quota: ${GPU_QUOTA%%.*} vCPU"
fi
echo ""


# STATE BUCKET
# Terraform cannot create its own backend, so it is bootstrapped here. The account
# ID makes the globally-unique bucket name collision-free in any AWS account.

echo "→ Checking the Terraform state bucket..."

if aws s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
    echo "  Already exists."
else
    echo "  Creating ${STATE_BUCKET}..."

    # us-east-1 rejects a LocationConstraint; every other region requires one.
    if [ "$REGION" = "us-east-1" ]; then
        aws s3api create-bucket --bucket "$STATE_BUCKET" --region "$REGION" >/dev/null
    else
        aws s3api create-bucket --bucket "$STATE_BUCKET" --region "$REGION" \
            --create-bucket-configuration LocationConstraint="$REGION" >/dev/null
    fi

    aws s3api put-bucket-versioning --bucket "$STATE_BUCKET" \
        --versioning-configuration Status=Enabled

    aws s3api put-bucket-encryption --bucket "$STATE_BUCKET" \
        --server-side-encryption-configuration \
        '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'

    aws s3api put-public-access-block --bucket "$STATE_BUCKET" \
        --public-access-block-configuration \
        "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

    echo "  Created with versioning, encryption and public access blocked."
fi
echo ""

# Backend settings for this account. Written to disk so that plain terraform
# commands can be re-run by hand later with -backend-config=backend.hcl.
cat > "${REPO_ROOT}/terraform/backend.hcl" <<EOF
bucket = "${STATE_BUCKET}"
region = "${REGION}"
EOF

cd "${REPO_ROOT}/terraform"

echo "→ Initialising Terraform..."
terraform init -reconfigure -backend-config=backend.hcl
echo ""

# Step 1: ECR must exist before images can be pushed. A plain full apply would
# create the task definition referencing images that aren't in ECR yet, leaving
# the first request to fail with an image-pull error. So create ECR first.
echo "→ Step 1/3: Creating the ECR repository (terraform apply -target=module.ecr)..."
if ! confirm_step "Apply ECR repository?"; then
    echo "  Cancelled. Nothing was applied."
    exit 0
fi
terraform apply -target=module.ecr -auto-approve
echo ""

# Step 2: build and push the vllm + proxy images into the now-existing repo.
# The repository URL comes straight from the Terraform output, so the build script
# can never push to a different repository or region than the one ECS reads from.
# Docker layer caching makes repeat runs fast (the model-download layer is reused
# unless the Dockerfile or HF_TOKEN changes), and ECR skips layers it already has.
echo "→ Step 2/3: Building and pushing container images..."
"${REPO_ROOT}/scripts/build_and_push.sh" "$(terraform output -raw ecr_repository_url)"
echo ""

# Step 3: apply the rest of the stack.
echo "→ Step 3/3: Planning the remaining infrastructure..."
terraform plan -out=tfplan
echo ""

if ! confirm_step "Apply these changes?"; then
    rm -f tfplan
    echo "  Cancelled. ECR and images exist, but the rest of the stack was not applied."
    exit 0
fi

echo "→ Applying infrastructure..."
terraform apply tfplan
rm -f tfplan
echo ""

echo "  Deployment Complete!"
echo ""

terraform output
echo ""
echo "  The API key is hidden above. Print it with:"
echo "  cd terraform && terraform output -raw public_api_key"
